# Generated by Django 4.2.17 on 2024-12-22 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_snippet_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='tags',
            new_name='tag',
        ),
    ]
