# Generated by Django 4.2.17 on 2024-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_rename_tags_snippet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='existence_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
