# Generated by Django 4.2.17 on 2024-12-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_snippet_existence_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='existence_status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='note.tag'),
        ),
    ]
